name=MGRS
version=1.1.0
author=Cold Bore Research & Development
maintainer=Cold Bore Research & Development
sentence=WGS84 Latitude Longitude to UTM and MGRS converter for embedded Arduino platforms.
paragraph=Lightweight MGRS conversion library derived from standard WGS84 UTM/MGRS algorithms.
category=Data Processing
url=https://github.com/ColdBore-RD/ubiquitous-palm-tree
architectures=*